<a href="https://colab.research.google.com/github/mhamzaraheel/pytorch_DeepLearning/blob/main/NooteBooks/1_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>




# Pytorch Fundamentals



## What is PyTorch?

[PyTorch](https://pytorch.org/) is an open source machine learning and deep learning framework taht provides a flexible and dynamic computational graph, which is particularly well-suited for deep learning tasks.


## Organizations make use of PyTorch?

- Widely adopted by major technology companies including [Meta (Facebook)](https://ai.facebook.com/blog/pytorch-builds-the-future-of-ai-and-machine-learning-at-facebook/), Tesla, and Microsoft, as well as prominent AI research institutions like [OpenAI](https://openai.com/blog/openai-pytorch/) plays a crucial role in driving research initiatives and integrating machine learning capabilities into various products.

- Andrej Karpathy (head of AI at Tesla) has given several talks ([PyTorch at Tesla](https://youtu.be/oBklltKXtDE), [Tesla AI Day 2021](https://youtu.be/j0z4FweCy4M?t=2904)) about how Tesla use PyTorch to power their self-driving computer vision models.

- PyTorch is also used in other industries such as agriculture to [power computer vision on tractors](https://medium.com/pytorch/ai-for-ag-production-machine-learning-for-agriculture-e8cfdb9849a1).

## Why use PyTorch?

Machine learning researchers love using PyTorch. And as of September 2023, PyTorch is the [most used deep learning framework on Papers With Code](https://paperswithcode.com/trends), a website for tracking machine learning research papers and the code repositories attached with them.

PyTorch also helps take care of many things such as GPU acceleration (making your code run faster) behind the scenes.

So you can focus on manipulating data and writing algorithms and PyTorch will make sure it runs fast.



In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
torch.__version__

'2.1.0+cu118'

## 1.Introduction to tensors


Tensors are the fundamental building block of machine learning.

Their job is to represent data in a numerical way.

For example, you could represent an image as a tensor with shape `[3, 224, 224]` which would mean `[colour_channels, height, width]`, as in the image has `3` colour channels (red, green, blue), a height of `224` pixels and a width of `224` pixels.


![First_Image](https://github.com/mhamzaraheel/pytorch_DeepLearning/blob/main/Images/1%23tensor-shape-example-of-image.png?raw=true)





### 1.1 Creating Tensor
PyTorch has such a strong affinity for tensors that an entire documentation page is devoted to the [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) class.

> The first one  is **scalar**.                                                                   
                                                                               A scalar is a single number and in  it's a zero dimension tensor.

In [2]:
# Scaler
scaler = torch.tensor(5)
scaler

tensor(5)

This is how we can get the item (integer) of scaler tensor - `torch.item()`

**Note** Only work with one elemnt tensor

In [3]:
# get the item of tensor
scaler.item()

5

We can also check the dimension of tesnor using `ndim` attribute.

In [4]:
# dimension of the sacler tensor
scaler.ndim

0

Another important concept for tensors is their `shape` attribute. The shape tells you how the elements inside them are arranged.

**Note** scaler have no shape

In [5]:
# shape of the scaler tensor (scaler has no shape)
scaler.shape

torch.Size([])

> The second one is  **vector**.                                                
  A vector is a single dimension tensor but can contain many numbers.


In [6]:
# vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [7]:
# getting the item of the vector tensor
print("First Item = ",vector[0])
print("Second Item = ",vector[1])

First Item =  tensor(1)
Second Item =  tensor(2)


In [8]:
# dimension of the vector tensor
vector.ndim

1

In [9]:
# shape of the vector tensor
vector.shape

torch.Size([2])

> Now we wil create the  **MATRIX**.                                       
  MATRIX same as Vecotr but get a extra dimension.   
  MATRIX has two dimension (2d).

In [10]:
# MATRIX
MATRIX = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
MATRIX

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [11]:
MATRIX[0],MATRIX[1]

(tensor([1, 2]), tensor([3, 4]))

In [12]:
# dimension of the MATRIX tensor
MATRIX.ndim

2

In [13]:
# shape of the MATRIX Tensor
MATRIX.shape

torch.Size([3, 2])

> Now what about the **TESNOR** ?                                          
  TENSOR can be of multiple dimensions.


In [14]:
#TENSOR
TENSOR = torch.tensor([[[1,2],
                        [3,4],
                        [5,6]]])
TENSOR

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [15]:
# dimension of the TENSOR
TENSOR.ndim

3

In [16]:
# shape of the TENSOR
TENSOR.shape

torch.Size([1, 3, 2])

In [17]:
TENSOR[0]

tensor([[1, 2],
        [3, 4],
        [5, 6]])

Here below is the Represenatiom of the dimensions.

![second_Image](https://github.com/mhamzaraheel/pytorch_DeepLearning/blob/main/Images/1%23-pytorch-different-tensor-dimensions.png?raw=true)

Let's summarise.

| Name | What is it? | Number of dimensions | Lower or upper (usually/example) |
| ----- | ----- | ----- | ----- |
| **scalar** | a single number | 0 | Lower (`a`) |
| **vector** | a number with direction | 1 | Lower (`y`) |
| **matrix** | a 2-dimensional array of numbers | 2 | Upper (`Q`) |
| **tensor** | an n-dimensional array of numbers | can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | Upper (`X`) |

![Third_Image](https://github.com/mhamzaraheel/pytorch_DeepLearning/blob/main/Images/1%23-scalar-vector-matrix-tensor.png?raw=true)

### 1.2 Random Tensors

Above we have created the Tensors (for the representation of data) by hand, but in machine learning we dont need to create the tensor by hand.

Instead Neural Network learn in the way they start with the random numbers `weights and bias` and then start fitting te those random numbers to better representation of the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

How can we create the tensors of random numbers?

Lets create with [`torch.rand()`]( https://pytorch.org/docs/stable/generated/torch.rand.html)

In [18]:
# create a random tensor interval[0,1] of size(2,3)
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.0904, 0.3509, 0.7293],
        [0.3561, 0.0027, 0.0671]])

We can create the tensor of different shape by adjusting the `size` parameter

For example, we can create the tensor of common image shape of `[28, 28, 3]` (`[height, width, color_channels`]).

In [19]:
# create random tensor like a image
random_image_tensor = torch.rand(size = (3,28,28))
random_image_tensor.shape , random_image_tensor.ndim

(torch.Size([3, 28, 28]), 3)

### 1.3 zeros & ones

Let's create a tensor full of zeros with [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html)

Let's create a tensor full of ones with [`torch.ones()`](https://pytorch.org/docs/stable/generated/torch.ones.html#torch.ones)


In [20]:
# create a tensor of all zeros
zeros   = torch.zeros(2,2)
zeros

tensor([[0., 0.],
        [0., 0.]])

In [21]:
# create a tensor of all oes
ones   = torch.ones(2,2)
ones

tensor([[1., 1.],
        [1., 1.]])

### 1.4 zeroslike & oneslike

We can create tensor of all zeros with the same shape as a XYZ tensor.

To do so you can use [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) or [`torch.ones_like(input)`](https://pytorch.org/docs/1.9.1/generated/torch.ones_like.html) which return a tensor filled with zeros or ones in the same shape as the `input` respectively.

In [22]:
# create a uninitialized  tensor
empty = torch.empty(2,5)
empty

tensor([[-8.7096e-03,  3.2293e-41, -1.0888e-02,  3.2293e-41,  0.0000e+00],
        [ 1.8750e+00,  0.0000e+00,  1.8750e+00,  0.0000e+00,  0.0000e+00]])

In [23]:
# create the tensor of all zeros same like empty tensor
ten_zeros = torch.zeros_like(empty)
ten_zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [24]:
# create the tensor of all ones same like empty tensor
ten_ones = torch.ones_like(empty)
ten_ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### 1.5 range and arrange


We may need to create the tensor of some numbers bw the range , such as 1 to 10 or 0 to 100.

You can use [`torch.arange(start, end, step)`](https://pytorch.org/docs/stable/generated/torch.arange.html#torch.arange) to do so.

Where:
* `start` = start of range (e.g. 0)
* `end` = end of range (e.g. 10)
* `step` = how many steps in between each value (e.g. 1)

> **Note:** In Python, you can use `range()` to create a range. However in PyTorch, [`torch.range()`](https://pytorch.org/docs/stable/generated/torch.range.html#torch.range)` is deprecated and may show an error in the future.


In [25]:
# create the tensor of range (from 1 to 9)
one_to_ten = torch.range(start = 1 , end = 10 , step = 1)
one_to_ten

<ipython-input-25-61dc7f33f4f9>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(start = 1 , end = 10 , step = 1)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
# create the tensor of range (from 1 to 9)
one_to_ten = torch.arange(start = 1 , end = 10 , step = 1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1.6 Randoom Permutation

We can also create the tensor of random permutation of integers from 0 to n - 1

For this use the [`torc.randperm()`](https://pytorch.org/docs/stable/generated/torch.randperm.html#torch.randperm)





In [27]:
# create the tensor of random permutation of integers from 0 to n - 1.

random_perm = torch.randperm(5)
random_perm

tensor([0, 2, 3, 1, 4])

### 1.6 Random Integers


[`torch.randint`](https://pytorch.org/docs/stable/generated/torch.randint.html#torch.randint) generates random integers between the [low,high] of specified size .

`low` : The lower bound.

`high` :The upper bound.

`size` : The shape of the output tensor.


In [28]:
# create the tensor of integer  interval[3,5] of size(3)
torch.randint(3, 5, (3,))

tensor([3, 4, 4])

In [29]:
# create the tensor of integer  interval[0,8] of size(2,2)
torch.randint(8, (2, 2))

tensor([[5, 2],
        [0, 7]])

In [30]:
# create the tensor of integer  interval[5,10] of size(2,2)
torch.randint(5, 10, (2, 2))

tensor([[6, 8],
        [7, 5]])

### 1.7 Tensor datatypes


There are many different [tensor datatypes in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types).

**Note:** we face many time the following errors
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

> Tensors on which we are performing operations are of same datatye, and on same device .                        
  Some operations require the specific shape rule.

In [31]:
float_32_tensor = torch.tensor([2.,3.,4.],
                               dtype = None, # data type of the tensor
                               device = None, # on which device your tensor
                               requires_grad = True) # want to track the gradients or not with this tesor operations

float_32_tensor

tensor([2., 3., 4.], requires_grad=True)

In [32]:
float_32_tensor.dtype

torch.float32

In [33]:
# convert the data type from float32 to float16
float_16_tensor =  float_32_tensor.type(torch.float16)
float_16_tensor


tensor([2., 3., 4.], dtype=torch.float16, grad_fn=<ToCopyBackward0>)

## 2.Tensor Information (Tensor Attributes)

1. Tensors not right datatype - to do get datatype of a tensor, we can use `tensor.dtype`
2. Tensors not right shape - to get shape of a tensor, we can use `tensor.shape`
3. Tensors not on the right device - to get device of a tensor,we can use `tensor.device`

In [34]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9570, 0.3697, 0.0180, 0.1580],
        [0.3259, 0.2093, 0.1984, 0.1066],
        [0.7739, 0.3862, 0.5825, 0.3467]])

In [35]:
# gettin infromation of tensor
print(f"""Datatype of the Tensor: {random_tensor.dtype}
Shape of the Tensor: {random_tensor.shape}
Device of the Tensor: {random_tensor.device} \n """)

Datatype of the Tensor: torch.float32
Shape of the Tensor: torch.Size([3, 4])
Device of the Tensor: cpu 
 


## 3.Different Tensor Operations

Tensor opertions include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

### 3.1 Basic operations

Let's start with a few of the fundamental operations, addition (`+`), subtraction (`-`), mutliplication (`*`).


In [36]:
some_tensor =  torch.tensor([[1,2,3],
                          [4,5,6]])
some_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [37]:
# add 5 to the  every elemnt
some_tensor + 5

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [38]:
# Bulit in function
torch.add(some_tensor , 5)

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [39]:
# subtract the 5 from every elemnt
some_tensor - 5

tensor([[-4, -3, -2],
        [-1,  0,  1]])

In [40]:
# Multiply every elemnt with 5
some_tensor * 5

tensor([[ 5, 10, 15],
        [20, 25, 30]])

In [41]:
# Bulit in function for multiplication
torch.mul(some_tensor,5)

tensor([[ 5, 10, 15],
        [20, 25, 30]])

### 3.2 Sum of all the items/elements of tensor

**Resource** - Here is [`torch.sum`](https://pytorch.org/docs/stable/generated/torch.sum.html).


In [42]:
# MATRIX (2-dimensional)
tensor_2d =torch.tensor([[1,2,3],
                          [4,5,6]])

In [43]:
torch.sum(tensor_2d, dim=0) # dim = 0 -> Column wise summation

tensor([5, 7, 9])

In [44]:
torch.sum(tensor_2d, dim=1) # dim = 1 -> Row wise summation

tensor([ 6, 15])

In [45]:
# TENSOR (3-dimensional)
tensor_3d = torch.arange(2 * 2 * 3).view(2, 2, 3)
tensor_3d

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [46]:
torch.sum(tensor_3d, 0)  # dim = 0 -> Summation along th 0th dimension

tensor([[ 6,  8, 10],
        [12, 14, 16]])

In [47]:
torch.sum(tensor_3d, (0,1)) # firstly summation along the 0th dimension & then along column wise

tensor([18, 22, 26])

In [48]:
torch.sum(tensor_3d, (0,2))  # firstly summation along the 0th dimension & then along row wise

tensor([24, 42])

In [49]:
# TENSOR (3-dimensional)
tensor_3d = torch.arange(2 * 2 * 3).view(2, 2, 3)
tensor_3d

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [50]:
torch.sum(tensor_3d, 1)  # dim = 1 -> Column wise summation

tensor([[ 3,  5,  7],
        [15, 17, 19]])

In [51]:
torch.sum(tensor_3d, (1,0))  # firstly Column wise summation & then Column wise summation

tensor([18, 22, 26])

In [52]:
torch.sum(tensor_3d, (1,2)) # firstly Column wise summation   & then Row wise summation

tensor([15, 51])

In [53]:
# TENSOR (3-dimensional)
tensor_3d = torch.arange(2 * 2 * 3).view(2, 2, 3)
tensor_3d

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [54]:
torch.sum(tensor_3d, 2)  # dim = 2 -> Row wise summation

tensor([[ 3, 12],
        [21, 30]])

In [55]:
torch.sum(tensor_3d, (2,0)) # firstly Row wise summation   & then Column wise summation

tensor([24, 42])

In [56]:
torch.sum(tensor_3d, (2,1)) # firstly Row wise summation   & then Row wise summation

tensor([15, 51])

### 3.3 Matrix Multiplication



 [Matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html) is the most common operation in machine learing and deep learning.

> **Note:** A matrix multiplication is also refered as [**dot product**](https://www.mathsisfun.com/algebra/vectors-dot-product.html) of two matrices.


In the PyTorch, we can use [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) method to impliment the matrix multiplication functionality.

>Matrix Multiplication rule must fulfil:                   
 The **inner dimensions** must match:
  * `(4, 3) @ (4, 3)` won't work
  * `(2, 4) @ (4, 2)` will work
  * `(3, 2) @ (2, 3)` will work

>The resulting matrix will have the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

> **Note:** "`@`" in Python is the symbol for matrix multiplication.

> **Resource:** Here is the comple guide for matrix multiplication using `torch.matmul()` [in the PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.matmul.html).




In [57]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

*The difference between element-wise multiplication and matrix multiplication is the addition of values*.

> Element-wise multiplication involves multiplying corresponding elements of two matrices, resulting in a new matrix with the same dimensions.

> Matrix multiplication is a new matrix, where each element is obtained by taking the sum of the products of corresponding elements.



 Below is the representation of the how both work for a `tensor` variable with values `[1, 2, 3]`:

| Operation | Calculation | Code |
| ----- | ----- | ----- |
| **Element-wise multiplication** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tensor * tensor` |
| **Matrix multiplication** | `[1*1 + 2*2 + 3*3]` = `[14]` | `tensor.matmul(tensor)` |


In [58]:
# Elemet wise multiplication of two tensors
tensor * tensor

tensor([1, 4, 9])

In [59]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [60]:
# @ can be used for the matmul , but not recomended
tensor @ tensor

tensor(14)

We can face the error `shape mismatch` during matrix multiplication.

Matrix multiplication matrices have a strict rule about what shapes and sizes can be combined.

In [62]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

Now we will do the matrix multplication between  `tensor_A` and `tensor_B` by making their inner dimensions match.

**Transpose** can switch the dimensions of the tensors.

You can perform transposes in PyTorch using either:
* [`torch.transpose(input, dim0, dim1)`](https://pytorch.org/docs/stable/generated/torch.transpose.html) - where `input` is the desired tensor to transpose and `dim0` and `dim1` are the dimensions to be swapped.
* [`tensor.T`](https://pytorch.org/docs/stable/generated/torch.t.html) - where `tensor` is the desired tensor to transpose.

In [63]:
# tensor beofre transpose
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [64]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [65]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape},                 tensor_B = {tensor_B.shape}\n")
print(f"New shapes:      tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Matrix Multiplication: {tensor_A.shape} * {tensor_B.T.shape} <- Here the inner dimensions match\n")
print("Mtrix Multiplication OutPut:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]),                 tensor_B = torch.Size([3, 2])

New shapes:      tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Matrix Multiplication: torch.Size([3, 2]) * torch.Size([2, 3]) <- Here the inner dimensions match

Mtrix Multiplication OutPut:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


We can also use [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html) which is a alias for `torch.matmul()`.

In [66]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

How the Matrix Multiplication look like ?

![Visual Demo](https://github.com/mhamzaraheel/pytorch_DeepLearning/blob/main/Images/1%23-matrix-multiply.gif?raw=true)

 Matrix Multiplication Visualzation - http://matrixmultiplication.xyz.




## 4.Min, Max and Mean (Aggregation)
▶ **Resource** = we can find the min, max and mean by using the  > [`torch.min()`](https://pytorch.org/docs/stable/generated/torch.min.html) ,
[`torh.max()`](https://pytorch.org/docs/stable/generated/torch.min.html) ,
[`torch.mean()`](https://pytorch.org/docs/stable/generated/torch.mean.html) respectively.

In [67]:
x_tensor = torch.arange(0,10,1)
x_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
print(f"Min: ",x_tensor.min())
print(f"Min: ",x_tensor.max())
print(f"Min: ",x_tensor.type(torch.float).mean())

Min:  tensor(0)
Min:  tensor(9)
Min:  tensor(4.5000)


**Note:** We get the error as `torch.mean()` require tensors to be in `torch.float` or `torch.Long` . So we firslt

You can also do the same as above with `torch` methods.

In [69]:
torch.min(x_tensor) , torch.max(x_tensor) , torch.mean(x_tensor.type(torch.float))

(tensor(0), tensor(9), tensor(4.5000))

We can also find the min mix and mean along the dimensions (See the Documentation)

## 5.Positional min/max

Some time we need to find the index where the min and max occurs we can find it as  [`torch.argmax()`](https://pytorch.org/docs/stable/generated/torch.argmax.html) and [`torch.argmin()`](https://pytorch.org/docs/stable/generated/torch.argmin.html) respectively.


In [70]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index of min value: {tensor.argmin()}")
print(f"Index of max value: {tensor.argmax()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index of min value: 0
Index of max value: 8


## 6.Reshaping, Stacking, Squeezing and Unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:



[`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) > Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`.

[`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) > Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
[`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) > Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size.

[`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) > Squeezes `input` to remove all the dimenions with value `1`(removes all 1 dimensions from a tensor).

[`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) >  Returns `input` with a dimension value of `1` added at `dim`(add a 1 dimension to a target tensor).

[`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) > Returns a *view* of the original `input` with its dimensions permuted (swapped) to `dims`.

Why do any of these?

*To get rid of shape misamtch errors.*

> Reshape the tensor into new shape `torch.reshape()`.
For Better understadig see the documentation and practice all.

In [71]:
# Creat the tensor
x = torch.arange(1,11)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
# Reshape the tensor
x.reshape(2,5)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [73]:
# Same as above
torch.reshape(x,(2,5))

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

> We can also change the view with `torch.view()`.

In [74]:
x.view(2,5)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

> If we want to stack different tensors, we could do so with `torch.stack()` "Size must same".

In [75]:
# Stack tensors on top of each other
torch.stack([x,x,x], dim = 0)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [76]:
# Stack tensors on top of each other
torch.stack([x,x,x], dim = 1)

tensor([[ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]])


>Can remove all single dimensions from a tensor?
To do so you can use `torch.squeeze()`

In [77]:
#  Before squeezing
reshaped_tensor = x.reshape(1,10)
reshaped_tensor , reshaped_tensor.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [78]:
# after squeezing, remove the 1-dim
reshaped_tensor.squeeze() , reshaped_tensor.squeeze().shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

> You can also use `torch.unsqueeze()` to add a dimension value of 1 at a specific index.

In [79]:
reshaped_tensor,reshaped_tensor.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [80]:
# Add an extra dimension with unsqueeze
reshaped_tensor.unsqueeze(dim=0) , reshaped_tensor.unsqueeze(dim=0).shape

(tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]]), torch.Size([1, 1, 10]))

In [81]:
# Add an extra dimension with unsqueeze
reshaped_tensor.unsqueeze(dim=2) , reshaped_tensor.unsqueeze(dim=2).shape

(tensor([[[ 1],
          [ 2],
          [ 3],
          [ 4],
          [ 5],
          [ 6],
          [ 7],
          [ 8],
          [ 9],
          [10]]]),
 torch.Size([1, 10, 1]))

>  You can also swap the order of axes values with `torch.permute(input, dims)`.

In [82]:
# original tensor
some_tensor = torch.rand(3,28,28)
some_tensor.shape

torch.Size([3, 28, 28])

In [83]:
some_tensor.permute(2,0,1).shape

torch.Size([28, 3, 28])

## 7.Indexing (selecting specific data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

Indexing can help here.

In [84]:
x = torch.arange(1,16).reshape (1,3,5)
x

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]]])

In [85]:
# get the 0th index of 0th dimension
x[0]

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])

In [86]:
# get the 0th index of 1st dimension
x[0][0],x[0,0]

(tensor([1, 2, 3, 4, 5]), tensor([1, 2, 3, 4, 5]))

In [87]:
# get the 0th index of 2nd dimension
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

We can also use `:` to specify "all values in this dimension" and then use a comma (`,`) to add another dimension.

In [88]:
# get all values of the 0th dimension and 3rd index of 1st dimension
x[:,2]

tensor([[11, 12, 13, 14, 15]])

In [89]:
# get all the values of 0th dimension & first dimension , and 2nd index of 3rd dimension
x[:,:,1]

tensor([[ 2,  7, 12]])

In [90]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([7])

## 8.PyTorch Tensors & NumPy Arrays

Sometimes we need to swap between the numpy and  pytorch.

The two main methods we'll  use for NumPy to PyTorch (and vice vers) are:
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor.
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.



In [91]:
import numpy

array  = np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
# Numpy array to torch tensor
tensor = torch.from_numpy(array)
tensor , array

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

If we change the tensor , there will be no effect in the array.

In [93]:
# Torch tensor to numpy array
array = tensor.numpy()
array , tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

## 9.Reproducibilty (`torch.manual_seed(seed)`)


Although random numbers(randomness) is nice and powerful, sometimes you'd like there to be generate the same random number in each time you run the code (little_less_randomness).

*Why we need litle_less_randomness?*

So we can perform repeatable experiments on the same Radom numbers(randomness).

For example, you have created  an algorithm capable of achieving some X data performance. And then your friend tries to verify it.                                       
 *How could you do such a thing?*

That's where **reproducibility** comes in.

In other words, we can you get the same (or very similar) results on different computer.


**Resource:** Here is the [The PyTorch reproducibility documentation](https://pytorch.org/docs/stable/notes/randomness.html).


In [94]:
# Creat the two random tensors
tensor_x = torch.rand(3,3)
tensor_y = torch.rand(3,3)

print(tensor_x)
print("\n")
print(tensor_y)
# Now check if they are equal or not
print("\n")
tensor_x == tensor_y

tensor([[0.2391, 0.7399, 0.8463],
        [0.3826, 0.7392, 0.1296],
        [0.1648, 0.2451, 0.5992]])


tensor([[0.7277, 0.1344, 0.0548],
        [0.6459, 0.0130, 0.4335],
        [0.2083, 0.3876, 0.3694]])




tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

As you can see above , both the tensors are of different values.

How if you want to generate the two random tesor having the *same* value.

That's where [`torch.manual_seed(seed)`](https://pytorch.org/docs/stable/generated/torch.manual_seed.html) comes in, where `seed` is an integer (like `42` but it could be anything) that flavours the randomness.

In [95]:
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(seed = RANDOM_SEED)

tensor_A = torch.rand(3,3)
print(tensor_A,"\n")

torch.manual_seed(seed = RANDOM_SEED) # without this second tensor will be diffrent fron one.

tensor_B= torch.rand(3,3)
print(tensor_B)


# check if they both are equal or not.


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]]) 

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


## 10.Running tensors on GPUs (and making faster computations)

GPUs are crucial in deep learning for parallel processing, accelerating complex operations and reducing training time. Their high memory bandwidth efficiently handles large datasets, making them essential for neural network computations and overall model performance.

In [96]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found




### 10.1 Getting PyTorch to run on the GPU

Once you've got a GPU ready to access, the next step getting pytorch so that we can use the gpu for processing.

To do so, you can use the [`torch.cuda`](https://pytorch.org/docs/stable/cuda.html) package.

You can test if PyTorch has access to a GPU using [`torch.cuda.is_available()`](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html#torch.cuda.is_available).


In [97]:
# Check for GPU
torch.cuda.is_available()

False

As you can see that if the output is False , it mean GPU is not available.

To make that our code run on CPU or GPU if it is available , we have a setup.

That's why , somene run the code , regardless of computing device they are using.

In [98]:
# it is the device agnostic code.

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

If we get the `cuda` then we can process by setting our code to available `CUDA` device, other wise it will go with the CPU.  

> **Note:** In PyTorch, it's best practice to write [**device agnostic code**](https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code). This means code that'll run on CPU (always available) or GPU (if available).

For more better Performance you can use multiple GPU.

You can count the number of GPUs PyTorch has access to using [`torch.cuda.device_count()`](https://pytorch.org/docs/stable/generated/torch.cuda.device_count.html#torch.cuda.device_count).

In [99]:
torch.cuda.device_count()

0

### 10.2 Putting tensors (and models) on the GPU

You can put tensors and models on a specific device by calling [`to(device)`](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html) on them. Where `device` is the target device you'd like the tensor (or model) to go to.

In [100]:
cpu_tensor = torch.tensor([1,2,3])
cpu_tensor, some_tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [101]:
gpu_tensor = cpu_tensor.to(device)   #it will convert into gpu , if it is available
gpu_tensor , gpu_tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

### 10.3 Moving tensors back to the CPU


Some time we need to move the tensor back to cpu, *How can we do this?*


For example, NumPy does not leverage the GPU.

Let's try using the [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) method on our `tensor_on_gpu`.

In [102]:
gpu_tensor.numpy()    # it will give the error if the gpu_tesor is on gpu

array([1, 2, 3])

In [103]:
gpu_tensor.device

device(type='cpu')

In [104]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = gpu_tensor.cpu()
tensor_back_on_cpu.device

device(type='cpu')